[colors.bright]
black = '#575653'
red = '#D14D41'
green = '#879A39'
yellow = '#D0A215'
blue = '#4385BE'
magenta = '#CE5D97'
cyan = '#3AA99F'
white = '#FFFCF0'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.dim]
black = '#575653'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#FFFCF0'

[colors.normal]
black = '#575653'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'    # rgb(32, 94, 166)
magenta = '#A02F6F'
cyan = '#24837B'
white = '#FFFCF0'

[colors.primary]
background = '#100F0F'
foreground = '#FFFCF0'
dim_foreground = '#FFFCF0'
bright_foreground = '#FFFCF0'

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
style = "Regular"

[font.normal]
family = "JetBrains Mono"

[font.offset]
y = 1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "{"
key = 28
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 25
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = 37
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 26
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "|"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 23
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 22
mods = "Alt"

[shell]
args = ["-l"]
program = "/usr/bin/zsh"
[window]
startup_mode = "Fullscreen"

[window.padding]
x = 8
y = 4
