[tools]
vivid = "latest"

[tasks.vivid-generate]
description = "generate the zsh colors config"
run = '''
cat <<EOF > zsh_plugins/vivid.plugin.zsh
export LS_COLORS='$(vivid generate vivid/flexoki-dark.yml)'
zstyle ':completion:*' list-colors \${(s.:.)LS_COLORS}
EOF
'''
