[tools]
bat = "latest"
go = "latest"
neovim = "latest"
node = "latest"
"ubi:openbao/openbao[exe=bao]" = "latest"
opentofu = "latest"
packer = "latest"
pkl = "latest"
pre-commit = "latest"
protoc = "latest"
protoc-gen-connect-go = "latest"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
pulumi = "latest"
ripgrep = "latest"
rust = "latest"
typst = "latest"
yt-dlp = "latest"
zellij = "latest"
zig = "latest"
bitwarden = "latest"
kubectl = "latest"
jq = "latest"
github-cli = "latest"
fzf = "latest"
fd = "latest"
difftastic = "latest"
elixir = "latest"
"aqua:rfjakob/gocryptfs" = "latest"
buf = "latest"
uv = "latest"
chezmoi = "latest"
golangci-lint = "latest"
