[colors.bright]
black = '#100F0F'
red = '#D14D41'
green = '#879A39'
yellow = '#D0A215'
blue = '#4385BE'
magenta = '#CE5D97'
cyan = '#3AA99F'
white = '#FFFCF0'

[colors.cursor]
text = 'CellBackground'
cursor = 'CellForeground'

[colors.dim]
black = '#100F0F'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#FFFCF0'

[colors.normal]
black = '#100F0F'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#FFFCF0'

[colors.primary]
background = '#100F0F'
foreground = '#FFFCF0'
dim_foreground = '#FFFCF0'
bright_foreground = '#FFFCF0'

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
